### PR TITLE
Enable CI

### PR DESCRIPTION
**Pull request by takaishi**

### CODE REVIEW

**Comment by hfm** [comment]
I suggest making `ci/ci.sh` availabre for use besides CI, namely, renaming `ci/ci.sh` to `run.sh`.

**Comment by takaishi** [comment]
> I suggest making `ci/ci.sh` availabre for use besides CI, namely, renaming `ci/ci.sh` to `run.sh`.

I agree to rename so I commited https://github.com/pepabo/consul-rpm-builder/pull/11/commits/29b4a3e1b64daa5a91ca48e59904762dfa8006f6 .

**Review by hfm — APPROVED** [review]
LGTM!

**Comment by takaishi** [comment]
thanks!

**Pull request merged**
